# Uncomment to enable encoder
# CONFIG_EC11=y
# CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
CONFIG_ZMK_KEYBOARD_NAME="CtrlYa_L58"
# Uncomment the following line to enable the Lily58 OLED Display
CONFIG_ZMK_DISPLAY=y

# Конфигурация сохранения настроек клавиатуры
CONFIG_SETTINGS=y
CONFIG_NVS=y
CONFIG_SETTINGS_NVS=y
CONFIG_ZMK_SETTINGS_SAVE_DEBOUNCE=60000

# Дополнительные настройки Bluetooth
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y  # Включает экспериментальные функции BLE
CONFIG_ZMK_BLE_PASSKEY_ENTRY=y          # Включает ввод числового ключа при подключении

# Настройки сна
CONFIG_ZMK_SLEEP=y #Разрешаем глубокий сон
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000 # 30 минут до сна
CONFIG_ZMK_IDLE_TIMEOUT=180000 # 3 минуты до легкого сна